# Generated by Django 5.2 on 2025-07-01 06:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_user_full_name_remove_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Growth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "moisture",
                    models.FloatField(
                        help_text="Soil moisture as a percentage (0-100)"
                    ),
                ),
                ("ph", models.FloatField(help_text="Soil pH level (e.g. 5.5 - 7.5)")),
                ("name", models.CharField(max_length=255)),
                ("height", models.FloatField(help_text="Plant height in cm")),
                ("date_of_plantation", models.DateField()),
                ("expected_maturity_time", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "growth",
                "verbose_name_plural": "growths",
                "db_table": "growth",
            },
        ),
    ]
