# Generated by Django 5.2 on 2025-07-01 06:13

from django.db import migrations
import random
from datetime import timedelta
from django.utils import timezone


def seed_growth_data(apps, schema_editor):
    Growth = apps.get_model('core', 'Growth')

    plant_names = [
        # Vegetables
        "Sukuma Wiki", "Cabbage", "Spinach", "Onion", "Tomato", "Kales", "Amaranth", "Cowpeas Leaves", "Managu",
        "Terere", "Pumpkin Leaves", "Mito", "Spider Plant", "Nightshade", "Coriander", "Dhania", "Chili", "Okra",

        # Legumes
        "Beans", "Green Grams", "Black Beans", "Lentils", "Pigeon Peas", "Soybeans", "Cowpeas",

        # Fruits
        "Mango", "Banana", "Pineapple", "Avocado", "Pawpaw", "Passion Fruit", "Watermelon", "Oranges", "Tangerine",
        "Lemon", "Guava", "Tree Tomato", "Strawberry",

        # Tubers and Roots
        "Potato", "Sweet Potato", "Arrowroot", "Yam", "Cassava",

        # Cereals & Grains
        "Maize", "Sorghum", "Millet", "Wheat", "Rice", "Barley", "Oats",

        # Herbs & Spices
        "Ginger", "Garlic", "Basil", "Mint", "Sage", "Thyme", "Rosemary",

        # Cash Crops
        "Tea", "Coffee", "Sugarcane", "Cotton", "Sunflower", "Macadamia", "Groundnut",

        # Others
        "Passion Fruit Vine", "Arrowroot", "Napier Grass", "Desmodium", "Tithonia", "Lucerne", "Mulberry"
    ]

    for _ in range(150):
        name = random.choice(plant_names)
        moisture = round(random.uniform(15.0, 85.0), 2)
        ph = round(random.uniform(5.5, 7.5), 2)
        height = round(random.uniform(5.0, 150.0), 2)

        date_of_plantation = timezone.now().date() - timedelta(days=random.randint(30, 120))
        expected_maturity_time = date_of_plantation + timedelta(days=random.randint(60, 120))

        Growth.objects.create(
            moisture=moisture,
            ph=ph,
            name=name,
            height=height,
            date_of_plantation=date_of_plantation,
            expected_maturity_time=expected_maturity_time,
        )

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_growth"),
    ]

    operations = [
        migrations.RunPython(seed_growth_data),
    ]
